OPENAI_API_KEY = "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"
ORS_API_KEY    = "5b3ce3597851110001cf6248e3d8b337bb364fd29f567c5ca7686430"
